name: OLX Scraper

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'JSON configuration for scraping'
        required: true
        type: string
        default: '{"brands":["BMW"],"models_by_brand":{},"fuel_types":["petrol"],"car_bodies":["sedan","suv","hatchback"],"gearbox_types":["manual","automatic"],"car_states":["used"],"price_min":5000,"price_max":50000,"year_min":2015,"year_max":2024,"km_min":0,"km_max":200000,"power_min":50,"power_max":500,"currency":"EUR","max_pages_per_brand":2}'
      session_id:
        description: 'Session ID for tracking'
        required: true
        type: string
        default: 'test-001'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v2
      with:
        install-chromedriver: true
        install-dependencies: true
        
    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 2
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install selenium==4.15.0 beautifulsoup4==4.12.2 requests==2.31.0 pandas==2.1.3 openpyxl==3.1.2 lxml==4.9.3 fake-useragent==1.4.0
        
    - name: Create GitHub config
      run: |
        cat > github-config.json << 'EOF'
        {
          "username": "miqq27",
          "repo": "olx-csv-data",
          "token": "ghp_cqyH9iB3GtSLfODzNTYXQdFkd3VQIl4PmGqf"
        }
        EOF
        
    - name: Run scraper
      run: |
        python scraper_dev_backup.py --config '${{ github.event.inputs.config }}' --session-id '${{ github.event.inputs.session_id }}'
      env:
        DISPLAY: :99
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scraping-results-${{ github.event.inputs.session_id }}
        path: "olx_results/*"
        if-no-files-found: warn
